/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gui;

import dao.DAOCliente;
import dao.DAOVenta;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author mario
 */
public class JIMReporte extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIMCliente
     */
    public JIMReporte() {
        initComponents();
        this.bgReportes.add(jrbConsulta1);
        this.bgReportes.add(jrbConsulta2);
        this.bgReportes.add(jrbConsulta3);
        deshabilitarCampoAnio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgReportes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlblRut = new javax.swing.JLabel();
        jtxtAnio = new javax.swing.JTextField();
        jrbConsulta1 = new javax.swing.JRadioButton();
        jrbConsulta2 = new javax.swing.JRadioButton();
        jrbConsulta3 = new javax.swing.JRadioButton();
        jbtnEjecutar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaReportes = new javax.swing.JTextArea();

        setClosable(true);
        setTitle("Listado de Reportes");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jlblRut.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jlblRut.setText("Año");

        jrbConsulta1.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jrbConsulta1.setText("1.- Total ventas Año");
        jrbConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbConsulta1ActionPerformed(evt);
            }
        });

        jrbConsulta2.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jrbConsulta2.setText("2.- Vehiculos más vendidos");
        jrbConsulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbConsulta2ActionPerformed(evt);
            }
        });

        jrbConsulta3.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jrbConsulta3.setText("3.- Cliente con más compras");
        jrbConsulta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbConsulta3ActionPerformed(evt);
            }
        });

        jbtnEjecutar.setText("Ejecutar");
        jbtnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEjecutarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbConsulta2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrbConsulta1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(60, 60, 60)
                        .addComponent(jlblRut))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrbConsulta3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnEjecutar))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlblRut, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrbConsulta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbConsulta2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbConsulta3)
                    .addComponent(jbtnEjecutar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jtxaReportes.setEditable(false);
        jtxaReportes.setColumns(20);
        jtxaReportes.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jtxaReportes.setForeground(new java.awt.Color(102, 0, 102));
        jtxaReportes.setRows(5);
        jScrollPane1.setViewportView(jtxaReportes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void limpiarCampos(){
        jtxtAnio.setEnabled(true);
        jtxtAnio.setText("");
        jrbConsulta1.setSelected(false);
        jrbConsulta2.setSelected(false);
        jrbConsulta3.setSelected(false);
        jtxaReportes.setText("");
    }
    
    private boolean validarSeleccion(){
        if(!jrbConsulta1.isSelected() || jtxtAnio.getText().isBlank()){
            return (
                    jrbConsulta2.isSelected() ||
                    jrbConsulta3.isSelected()
                    );    
        }else{
            return true;
        }
    }
    
    private void jbtnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEjecutarActionPerformed
        
        double venta = 0;
        jtxaReportes.setText("");
        
        if(validarSeleccion()){
            if(jrbConsulta1.isSelected()){
                int anio = Integer.parseInt(jtxtAnio.getText());
                venta = DAOVenta.valorVentasAnio(anio);
                jtxaReportes.setText("El total de venta para el año \n" + anio + " fue de "+ venta);
            }else if(jrbConsulta2.isSelected()){
                ArrayList<String> lista = DAOVenta.vehiculoMasVendidos();
                if(!lista.isEmpty()){
                    for (String registro : lista) {
                        jtxaReportes.append(registro);
                    }
                }else{
                    jtxaReportes.append("No existe registro de ventas!!!");
                }
            }else if(jrbConsulta3.isSelected()){
                ArrayList<String> lista = DAOVenta.clientesMasCompras();
                if(!lista.isEmpty()){
                    for (String registro : lista) {
                        jtxaReportes.append(registro);
                    }
                }else{
                    jtxaReportes.append("No existe registro de ventas!!!");
                }
            }
        }else{
            JOptionPane.showMessageDialog(null,"Todos los campos son obligatorios!!");
        }

    }//GEN-LAST:event_jbtnEjecutarActionPerformed

    private void habilitarCampoAnio(){
        this.jtxtAnio.setEnabled(true);
    }
    
    private void deshabilitarCampoAnio(){
        this.jtxtAnio.setEnabled(false);
    }
    
    private void jrbConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbConsulta1ActionPerformed
        if(jrbConsulta1.isSelected()){
            habilitarCampoAnio();
        }
    }//GEN-LAST:event_jrbConsulta1ActionPerformed

    private void jrbConsulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbConsulta2ActionPerformed
        deshabilitarCampoAnio();
    }//GEN-LAST:event_jrbConsulta2ActionPerformed

    private void jrbConsulta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbConsulta3ActionPerformed
        deshabilitarCampoAnio();
    }//GEN-LAST:event_jrbConsulta3ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        limpiarCampos();
    }//GEN-LAST:event_formComponentShown

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgReportes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnEjecutar;
    private javax.swing.JLabel jlblRut;
    private javax.swing.JRadioButton jrbConsulta1;
    private javax.swing.JRadioButton jrbConsulta2;
    private javax.swing.JRadioButton jrbConsulta3;
    private javax.swing.JTextArea jtxaReportes;
    private javax.swing.JTextField jtxtAnio;
    // End of variables declaration//GEN-END:variables
}
