/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gui;

import dao.DAOVehiculo;
import javax.swing.JOptionPane;
import model.Automovil;
import model.Camioneta;
import model.Vehiculo;

/**
 *
 * @author mario
 */
public class JIMVehiculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIMCliente
     */
    public JIMVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlblAtributo1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtMarca = new javax.swing.JTextField();
        jtxtPatente = new javax.swing.JTextField();
        jtxtModelo = new javax.swing.JTextField();
        jtxtAtributo1 = new javax.swing.JTextField();
        jbtnBuscar = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();
        jcbAtributo2 = new javax.swing.JCheckBox();
        jlblAtributo2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbcTipoVehiculo = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jbtnAgregar = new javax.swing.JButton();
        jbtnModificar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Administracion de Vehiculos");

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("Patente");

        jlblAtributo1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jlblAtributo1.setText("Rendimiento");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("Marca");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel4.setText("Modelo");

        jbtnBuscar.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jbtnBuscar.setText("Buscar");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        jbtnLimpiar.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jbtnLimpiar.setText("Limpiar");
        jbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimpiarActionPerformed(evt);
            }
        });

        jcbAtributo2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jcbAtributo2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jcbAtributo2.setContentAreaFilled(false);

        jlblAtributo2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jlblAtributo2.setText("¿Tiene AC?");

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel6.setText("Tipo Vehiculo");

        jcbcTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automovil", "Camioneta" }));
        jcbcTipoVehiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbcTipoVehiculoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbcTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jlblAtributo1)))
                            .addComponent(jlblAtributo2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtxtMarca)
                                .addComponent(jtxtModelo)
                                .addComponent(jtxtAtributo1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                            .addComponent(jtxtPatente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbAtributo2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnBuscar)
                            .addComponent(jbtnLimpiar))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbcTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnBuscar)
                    .addComponent(jtxtPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAtributo1)
                    .addComponent(jtxtAtributo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblAtributo2)
                    .addComponent(jcbAtributo2))
                .addGap(73, 73, 73))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));

        jbtnAgregar.setText("Agregar");
        jbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarActionPerformed(evt);
            }
        });

        jbtnModificar.setText("Modificar");
        jbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarActionPerformed(evt);
            }
        });

        jbtnEliminar.setText("Eliminar");
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jbtnAgregar)
                .addGap(27, 27, 27)
                .addComponent(jbtnModificar)
                .addGap(28, 28, 28)
                .addComponent(jbtnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnModificar)
                    .addComponent(jbtnAgregar)
                    .addComponent(jbtnEliminar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean validarCampos(){
        return !(jtxtPatente.getText().isBlank() ||
                jtxtMarca.getText().isBlank() ||
                jtxtModelo.getText().isBlank() ||
                jtxtAtributo1.getText().isBlank()
        );       
    }
    
    private Vehiculo getVehiculo(){
        Vehiculo vehiculo = null;

        if(validarCampos()){
            String patente = jtxtPatente.getText();
            String marca = jtxtMarca.getText();
            String modelo = jtxtModelo.getText();
            if(jcbcTipoVehiculo.getSelectedItem().toString().equalsIgnoreCase("Automovil")){
                double rendimiento = Double.parseDouble(jtxtAtributo1.getText());
                boolean aire = jcbAtributo2.isSelected();
                vehiculo = new Automovil(patente,marca,modelo,rendimiento,aire);
            }else{
                double capCarga = Double.parseDouble(jtxtAtributo1.getText());
                vehiculo = new Camioneta(patente,marca,modelo,capCarga);
            }
        }
        return vehiculo;
    }
    
    private void limpiarCampos(){
        jtxtPatente.setEnabled(true);
        jtxtPatente.setText("");
        jtxtMarca.setText("");
        jtxtModelo.setText("");
        jtxtAtributo1.setText("");
        jcbAtributo2.setSelected(false);
    }
    
    private void jbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarActionPerformed
        
        Vehiculo vehiculo = getVehiculo();
        if(vehiculo != null){
            if(DAOVehiculo.ingresar(vehiculo)){
                JOptionPane.showMessageDialog(null,"Vehiculo ingresado ok: " + vehiculo.getPatente());
                limpiarCampos();
            }else{
                JOptionPane.showMessageDialog(null,"Vehiculo no ingresado: " + vehiculo.getPatente());
            }
        }else{
            JOptionPane.showMessageDialog(null,"Todos los campos son obligatorios!!");
        }
    }//GEN-LAST:event_jbtnAgregarActionPerformed

    private void jbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarActionPerformed
        Vehiculo vehiculo = getVehiculo();
        
        if(vehiculo != null){
            if(DAOVehiculo.modificar(vehiculo)){
                JOptionPane.showMessageDialog(null,"Vehiculo modificado ok: " + vehiculo.getPatente());            
                this.jtxtPatente.setEnabled(true);
                limpiarCampos();
            }else{
                JOptionPane.showMessageDialog(null,"Vehiculo no modificado: " + vehiculo.getPatente());
            }
        }else{
            JOptionPane.showMessageDialog(null,"Todos los campos son obligatorios!!");
        }         
    }//GEN-LAST:event_jbtnModificarActionPerformed

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        Vehiculo vehiculo = null;
        
        if(!jtxtPatente.getText().isBlank()){
            String patente = jtxtPatente.getText();
            vehiculo = DAOVehiculo.existeVehiculo(patente);
            
                
            if(vehiculo != null){
                jtxtPatente.setEnabled(false);
                jtxtMarca.setText(vehiculo.getMarca());
                jtxtModelo.setText(vehiculo.getModelo());
            
                if(vehiculo instanceof Automovil ){
                    double rendimiento = ((Automovil) vehiculo).getRendimiento();
                    boolean tieneAire = ((Automovil) vehiculo).isTieneAire();
                    jtxtAtributo1.setText(""+rendimiento);
                    jcbAtributo2.setSelected(tieneAire);
                    jcbcTipoVehiculo.setSelectedIndex(0);
                }else{
                    double capCarga = ((Camioneta) vehiculo).getCapacidadCarga();
                    jtxtAtributo1.setText(""+capCarga);
                    jcbcTipoVehiculo.setSelectedIndex(1);
                }
                mostrarCamposPorVehiculo();
            }else{
                JOptionPane.showMessageDialog(null,"Vehiculo no existe " + patente);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Debe ingresar la patente!!!");
        }
        
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        Vehiculo vehiculo = getVehiculo();
        
        String patente;
        if(vehiculo != null){
            patente = vehiculo.getPatente();
            if(DAOVehiculo.eliminar(patente)){
                JOptionPane.showMessageDialog(null,"Vehiculo eliminado ok: " + patente);
                this.jtxtPatente.setEnabled(true);
                limpiarCampos();
            }else{
                JOptionPane.showMessageDialog(null,"Vehiculo no eliminado: " + patente);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Todos los campos son obligatorios!!");
        } 
        
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void mostrarCamposPorVehiculo(){
        int opcion = jcbcTipoVehiculo.getSelectedIndex();
        switch (opcion) {
            case 0 -> {
                jlblAtributo1.setText("Rendimiento");
                jlblAtributo2.setVisible(true);
                jlblAtributo2.setText("¿Tiene AC?");
                jcbAtributo2.setVisible(true);
            }
            case 1 -> {
                jlblAtributo1.setText("Cap. Carga ");
                jlblAtributo2.setVisible(false);
                jcbAtributo2.setVisible(false);
            }
        }
        
    }
    
    private void jcbcTipoVehiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbcTipoVehiculoItemStateChanged
        mostrarCamposPorVehiculo();
    }//GEN-LAST:event_jcbcTipoVehiculoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtnAgregar;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JButton jbtnModificar;
    private javax.swing.JCheckBox jcbAtributo2;
    private javax.swing.JComboBox<String> jcbcTipoVehiculo;
    private javax.swing.JLabel jlblAtributo1;
    private javax.swing.JLabel jlblAtributo2;
    private javax.swing.JTextField jtxtAtributo1;
    private javax.swing.JTextField jtxtMarca;
    private javax.swing.JTextField jtxtModelo;
    private javax.swing.JTextField jtxtPatente;
    // End of variables declaration//GEN-END:variables
}
