/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gui;

import dao.DAOEvento;
import javax.swing.JOptionPane;
import model.Evento;
import model.Fiesta;
import model.Matrimonio;

/**
 *
 * @author mario
 */
public class JIM_Evento extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIM_Cliente
     */
    public JIM_Evento() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtCodigo = new javax.swing.JTextField();
        jtxtDescripcion = new javax.swing.JTextField();
        jtxtAsistentes = new javax.swing.JTextField();
        jtxtRecinto = new javax.swing.JTextField();
        jbtbBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtbtnLimpiar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jcbTipoEvento = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jtxtNroMesas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtPrecio = new javax.swing.JTextField();
        jlblAtributo1 = new javax.swing.JLabel();
        jlblAtributo2 = new javax.swing.JLabel();
        jtxtAtributo2 = new javax.swing.JTextField();
        jcbxAtributo1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jbtnEliminar = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jbtnIngresar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Administracion de Eventos");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jbtbBuscar.setText("Buscar");
        jbtbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtbBuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("Codigo");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setText("Descripcion");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("#Asistentes");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel4.setText("Tam. Recinto");

        jtbtnLimpiar.setText("Limpiar");
        jtbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnLimpiarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel6.setText("Evento");

        jcbTipoEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fiesta", "Matrimonio" }));
        jcbTipoEvento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbTipoEventoItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel5.setText("#Mesas");

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel7.setText("Precio");

        jlblAtributo1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jlblAtributo1.setText("Alcohol?");

        jlblAtributo2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jlblAtributo2.setText("#DJ's");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jlblAtributo1)
                    .addComponent(jlblAtributo2)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtxtRecinto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtAsistentes, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtNroMesas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jtxtPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtAtributo2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(jtbtnLimpiar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addComponent(jtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jbtbBuscar))
                    .addComponent(jcbxAtributo1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jbtbBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtxtRecinto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtNroMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAtributo1)
                    .addComponent(jcbxAtributo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAtributo2)
                    .addComponent(jtxtAtributo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbtnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 0));

        jbtnEliminar.setText("Eliminar");
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });

        jbtnEditar.setText("Modificar");
        jbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarActionPerformed(evt);
            }
        });

        jbtnIngresar.setText("Ingresar");
        jbtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jbtnIngresar)
                .addGap(18, 18, 18)
                .addComponent(jbtnEditar)
                .addGap(18, 18, 18)
                .addComponent(jbtnEliminar)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEditar)
                    .addComponent(jbtnEliminar)
                    .addComponent(jbtnIngresar))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbTipoEventoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbTipoEventoItemStateChanged
        validarEquipos();
    }//GEN-LAST:event_jcbTipoEventoItemStateChanged

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        limpiarCampos();
    }//GEN-LAST:event_formComponentShown

    private boolean validarCampos(){
        return !(
                jtxtDescripcion.getText().isBlank() ||
                jtxtAsistentes.getText().isBlank() || 
                jtxtRecinto.getText().isBlank() || 
                jtxtNroMesas.getText().isBlank() ||
                jtxtPrecio.getText().isBlank() || 
                jtxtAtributo2.getText().isBlank());
    }
    
    private void limpiarCampos(){
        jtxtCodigo.setEnabled(true);
        jcbTipoEvento.setSelectedIndex(0);
        jtxtCodigo.setText("");
        jtxtDescripcion.setText("");
        jtxtAsistentes.setText("");
        jtxtRecinto.setText("");
        jtxtNroMesas.setText("");
        jtxtPrecio.setText("");
        jcbxAtributo1.setSelected(false);
        jtxtAtributo2.setText("");
    }
    
    private Evento getEvento(String codigo){
        
        try {
            if (validarCampos()){
                String descripcion = this.jtxtDescripcion.getText();
                int nroAsistentes = Integer.parseInt(this.jtxtAsistentes.getText());
                int recinto = Integer.parseInt(this.jtxtRecinto.getText());
                int nroMesas = Integer.parseInt(this.jtxtNroMesas.getText());
                double precio = Double.parseDouble(this.jtxtPrecio.getText());
                
                //fiesta
                boolean tieneAlcohol;
                int nroDj = 0;
                //matrimonio
                boolean tieneMusica;
                int nroPlatos = 0;

                Evento evento = null;
                
                if(this.jcbTipoEvento.getSelectedItem().toString().equalsIgnoreCase("Fiesta")){
                    tieneAlcohol = this.jcbxAtributo1.isSelected();
                    nroDj = Integer.parseInt(this.jtxtAtributo2.getText());
                    evento = new Fiesta(codigo, tieneAlcohol, nroDj, descripcion, 
                            nroAsistentes, recinto, nroMesas, precio );
                }else{
                    tieneMusica = this.jcbxAtributo1.isSelected();
                    nroPlatos = Integer.parseInt(this.jtxtAtributo2.getText());
                    evento = new Matrimonio(codigo, tieneMusica, nroPlatos, descripcion, 
                            nroAsistentes, recinto, nroPlatos, precio );
                }
                return evento;
            }
        } catch (NumberFormatException e) {
            System.out.println("Error de conversion: " + e.toString());
        }
        return null;
    }
    
    private void jbtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresarActionPerformed
        String codigo = "";
        Evento evento = getEvento(codigo);
        
        if (evento != null){
            if(DAOEvento.ingresar(evento)){
                JOptionPane.showMessageDialog(null,"Evento ingresado OK: " + evento.getCodigo() );
                limpiarCampos();
            }else{
                JOptionPane.showMessageDialog(null,"Evento no ingresado " + evento.getCodigo() );
            }
        }else{
            JOptionPane.showMessageDialog(null,"Todos los campos son obligatorios!!");
        }
    }//GEN-LAST:event_jbtnIngresarActionPerformed

    private void jtbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jtbtnLimpiarActionPerformed

    private void jbtbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtbBuscarActionPerformed
        
        if(!this.jtxtCodigo.getText().isBlank()){
            String codigo = jtxtCodigo.getText();
            Evento evento = DAOEvento.existeEquipo(codigo);
            
            if( evento != null ){
                this.jtxtCodigo.setEnabled(false);
                
                this.jtxtDescripcion.setText(evento.getDescripcion());
                this.jtxtAsistentes.setText(String.valueOf(evento.getCantidadAsistentes()));
                this.jtxtRecinto.setText(String.valueOf(evento.getTamanioRecinto()));
                this.jtxtNroMesas.setText(String.valueOf(evento.getCantidadMesas()));
                this.jtxtPrecio.setText(String.valueOf(evento.getPrecio()));
                
                if(evento instanceof Fiesta fiesta){
                    this.jcbTipoEvento.setSelectedIndex(0);
                    this.jcbxAtributo1.setSelected(fiesta.isTieneAlcohol());
                    this.jtxtAtributo2.setText(String.valueOf(fiesta.getNroDj()));
                }else if(evento instanceof Matrimonio matrimonio){
                    this.jcbTipoEvento.setSelectedIndex(1);
                    this.jcbxAtributo1.setSelected(matrimonio.isTieneMusica());
                    this.jtxtAtributo2.setText(String.valueOf(matrimonio.getCantPlatos()));
                }
            }else{
                JOptionPane.showMessageDialog(null,"El codigo evento no existe: " + codigo);
            }
        } else{
            JOptionPane.showMessageDialog(null,"Debe ingresar el codigo!!");
        }
    }//GEN-LAST:event_jbtbBuscarActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed
        String codigo = "";
        if (!this.jtxtCodigo.getText().isBlank()){
            codigo = this.jtxtCodigo.getText();
        }
        Evento evento = getEvento(codigo);
        
        if(evento != null){
            if(DAOEvento.actualizar(evento)){
                JOptionPane.showMessageDialog(null,"Evento modificado ok: " + evento.getCodigo());            
                this.jtxtCodigo.setEnabled(true);
                limpiarCampos();
            }else{
                JOptionPane.showMessageDialog(null,"Evento no existe: " + evento.getCodigo());
            }
        }else{
            JOptionPane.showMessageDialog(null,"Todos los campos son obligatorios!!");
        }  
    }//GEN-LAST:event_jbtnEditarActionPerformed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        String codigo = "";
        if (!this.jtxtCodigo.getText().isBlank()){
            codigo = this.jtxtCodigo.getText();
        }
        Evento equipo = getEvento(codigo);
         
        if(equipo != null){
            codigo = jtxtCodigo.getText();
            if(DAOEvento.eliminar(codigo)){
                this.jtxtCodigo.setEnabled(true);
                JOptionPane.showMessageDialog(null,"Evento eliminado OK: " + codigo);
                limpiarCampos();
            }else{
                JOptionPane.showMessageDialog(null,"Evento no existe: " + codigo);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Todos los campos son obligatorios!!");
        } 
    }//GEN-LAST:event_jbtnEliminarActionPerformed
    
    private void ocultarCampos(){
        this.jlblAtributo1.setVisible(false);
        this.jlblAtributo2.setVisible(false);
        this.jcbxAtributo1.setVisible(false);
        this.jtxtAtributo2.setVisible(false);
    }
    
    private void validarEquipos(){
        int opcion = this.jcbTipoEvento.getSelectedIndex();
        switch (opcion) {
            //fiesta
            case 0 -> {
                //Laptop
                this.jlblAtributo1.setText("Alcohol?");
                this.jlblAtributo2.setText("#DJ's");
            }
            //matrimonio
            case 1 -> {
                //Desktop
                this.jlblAtributo1.setText("Musica?");
                this.jlblAtributo2.setText("#Platos");
            }
            default -> {
                ocultarCampos();
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtbBuscar;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnIngresar;
    private javax.swing.JComboBox<String> jcbTipoEvento;
    private javax.swing.JCheckBox jcbxAtributo1;
    private javax.swing.JLabel jlblAtributo1;
    private javax.swing.JLabel jlblAtributo2;
    private javax.swing.JButton jtbtnLimpiar;
    private javax.swing.JTextField jtxtAsistentes;
    private javax.swing.JTextField jtxtAtributo2;
    private javax.swing.JTextField jtxtCodigo;
    private javax.swing.JTextField jtxtDescripcion;
    private javax.swing.JTextField jtxtNroMesas;
    private javax.swing.JTextField jtxtPrecio;
    private javax.swing.JTextField jtxtRecinto;
    // End of variables declaration//GEN-END:variables
}
