/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadoranotas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author mario
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcb_Asignatura = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jtxt_Nota1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxt_Nota2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxt_Nota3 = new javax.swing.JTextField();
        jtxt_porc1 = new javax.swing.JTextField();
        jtxt_porc2 = new javax.swing.JTextField();
        jtxt_porc3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlbl_promedio = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlbl_EstadoAlumno = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jbtnLimpiar = new javax.swing.JButton();
        jbtnCalcular1 = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculador de Notas");

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("Calculadora de Notas");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(167, 167, 167))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setText("Asignatura");

        jcb_Asignatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Ingles", "Modelamiento de datos", "Programacion de base de datos" }));

        jLabel3.setText("Nota1");

        jLabel4.setText("Nota2");

        jLabel5.setText("Nota3");

        jLabel6.setText("%");

        jLabel7.setText("%");

        jLabel8.setText("%");

        jLabel9.setText("Nota: Considerar las notas con formato de .");

        jLabel10.setText("Promedio");

        jlbl_promedio.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jlbl_promedio.setForeground(new java.awt.Color(255, 0, 0));
        jlbl_promedio.setText("0.0");

        jLabel11.setText("Estado Alumno");

        jlbl_EstadoAlumno.setForeground(new java.awt.Color(204, 0, 0));
        jlbl_EstadoAlumno.setText("-----------------");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jtxt_Nota1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                            .addComponent(jtxt_Nota2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtxt_Nota3, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jtxt_porc2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel7))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jtxt_porc3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jtxt_porc1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel6))))
                                    .addComponent(jcb_Asignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel9))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jlbl_promedio)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbl_EstadoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcb_Asignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxt_Nota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtxt_porc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxt_Nota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jtxt_porc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxt_Nota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_porc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jlbl_promedio)
                    .addComponent(jLabel11)
                    .addComponent(jlbl_EstadoAlumno))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(153, 255, 102));

        jbtnLimpiar.setBackground(new java.awt.Color(255, 255, 0));
        jbtnLimpiar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jbtnLimpiar.setText("Limpiar");
        jbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimpiarActionPerformed(evt);
            }
        });

        jbtnCalcular1.setBackground(new java.awt.Color(0, 153, 0));
        jbtnCalcular1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jbtnCalcular1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCalcular1.setText("Calcular");
        jbtnCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalcular1ActionPerformed(evt);
            }
        });

        jbtnSalir.setBackground(new java.awt.Color(255, 0, 0));
        jbtnSalir.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jbtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSalir.setText("Salir");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCalcular1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jbtnCalcular1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jbtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        System.exit(0);
        //dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
        
        //Se limpian los campos de las notas y porcentajes
        this.jtxt_Nota1.setText("");
        this.jtxt_Nota2.setText("");
        this.jtxt_Nota3.setText("");
        
        this.jtxt_porc1.setText("");
        this.jtxt_porc2.setText("");
        this.jtxt_porc3.setText("");
        
        this.jlbl_EstadoAlumno.setText("-----------------");
        this.jlbl_promedio.setText("0.0");
        
        //Se selecciona la primera opcion de la lista del combo box
        this.jcb_Asignatura.setSelectedIndex(0);
        
        //Pongo el cursor en elemento de ingreso de la nota1 para volver a ingresar
        this.jtxt_Nota1.requestFocus();
        
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    private void jbtnCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalcular1ActionPerformed
        double nota1 = 0;
        double nota2 = 0;
        double nota3 = 0;
        int porc1 = 0;
        int porc2 = 0;
        int porc3 = 0;
        
        if( validarAsignatura() ){

            try {
                nota1 = Double.parseDouble(this.jtxt_Nota1.getText());
                nota2 = Double.parseDouble(this.jtxt_Nota2.getText());
                nota3 = Double.parseDouble(this.jtxt_Nota3.getText());

                porc1 = Integer.parseInt(this.jtxt_porc1.getText());
                porc2 = Integer.parseInt(this.jtxt_porc2.getText());
                porc3 = Integer.parseInt(this.jtxt_porc3.getText());
                
                double notaPromedio = redondear( (nota1*porc1/100) + (nota2*porc2/100) + (nota3*porc3/100) );
                
                if(validarPorcentaje(porc1, porc2, porc3)){
                    if(validarRangoNotas(nota1, nota2, nota3)){
                        //Se debe realizar explicitamente esta conversiónd de tipos de double a String
                        String notaPromedioS = String.valueOf(notaPromedio);
                        this.jlbl_promedio.setText(notaPromedioS);
                        calcularEstado(notaPromedio);
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Las notas deben estar en el rago de 1-7");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Los ponderadores no suman 100%");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Un dato no pudo ser convertido a numero!!!");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una asignatura");
        }
    }//GEN-LAST:event_jbtnCalcular1ActionPerformed

    private boolean validarPorcentaje(int porc1, int porc2, int porc3){
        return (porc1+porc2+porc3) == 100;
    }
    private void calcularEstado(double notaFinal){
        if(notaFinal >= 4){
            this.jlbl_EstadoAlumno.setText("Aprobado");
            this.jlbl_EstadoAlumno.setForeground(Color.green);
        } else{
            this.jlbl_EstadoAlumno.setText("Reprobado");
            this.jlbl_EstadoAlumno.setForeground(Color.RED);
        }
    }
    private boolean validarAsignatura(){
        return this.jcb_Asignatura.getSelectedIndex() > 0;
    }
    
    private boolean validarRangoNotas(double nota1, double nota2, double nota3){

        if(nota1 >=1 && nota1 <=7){
            if(nota2 >= 1 && nota2 <=7 ){
                if(nota3 >=1 && nota3 <=7 ){
                    return true;
                }
            }
            
        }
        return false;
    }
    
    private static double redondear(double nota) {
        return Math.round(nota * 100.0)/100.0; //redondeo a 2 decimales^M
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jbtnCalcular1;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JComboBox<String> jcb_Asignatura;
    private javax.swing.JLabel jlbl_EstadoAlumno;
    private javax.swing.JLabel jlbl_promedio;
    private javax.swing.JTextField jtxt_Nota1;
    private javax.swing.JTextField jtxt_Nota2;
    private javax.swing.JTextField jtxt_Nota3;
    private javax.swing.JTextField jtxt_porc1;
    private javax.swing.JTextField jtxt_porc2;
    private javax.swing.JTextField jtxt_porc3;
    // End of variables declaration//GEN-END:variables
}
